### ISSUE TITLE
login should not be required

### ISSUE THREAD

**Issue by 3052** [fvrrvg/igo#1]
you can view public post without login:

https://www.instagram.com/p/C_e_VOXRa9C

**Comment by 3052** [comment]
found better tool
https://github.com/lostdusty/cobalt

**Comment by fvrrvg** [comment]
Good for you @3052.

Igo is designed as a full CLI tool for managing your Instagram account, allowing interaction with both public and private accounts. Unlike scraping, Igo uses Instagram API thanks to @ahmdrz & @Davincible , which requires logging in. This approach enables additional functionalities like downloading stories, highlights, and DMs from both private and public accounts.

I understand your point about downloading content from public accounts without logging in. However, Igo is built to function as a virtual device with a headless Instagram client, which requires authentication to perform these actions.

Have a great day!
